version: '2'
volumes:
    sense-data:
    nodered-data:
    grafana-data:
services:
  nodered:
    restart: always
    image: nodered/node-red
    volumes:
      - 'nodered-data:/data'
    ports:
      - "1880:1880"
  influxdb:
    restart: always
    image: influxdb:latest
    volumes:
      - 'sense-data:/data'
    ports:
      - "8086:8086"
  grafana:
    restart: always
    image: grafana/grafana:master
    environment:
#      - GF_PATHS_DATA=/data/
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=DoES
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    ports:
      - "80:3000"
    volumes:
      - 'grafana-data:/data'
    depends_on:
      - influxdb
  mosquitto:
    restart: always
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
#  bridge:
#    restart: always
#    build: ./bridge
#    depends_on:
#     - influxdb
#     - mosquitto
