



version: '2'
volumes:
    sense-data:
    nodered-data:
    grafana-data:
services:
  accesspoint:
    restart: always
    build: ./ap
    network_mode: host
    privileged: true
  nodered:
    restart: always
    build: ./nodered
    volumes:
      - 'nodered-data:/data'
    ports:
      - "1880:1880"
  influxdb:
    restart: always
    build: ./influxdb
    volumes:
      - 'sense-data:/data'
    ports:
      - "8086:8086"
  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - 'grafana-data:/data'
    depends_on:
      - influxdb
  mosquitto:
    restart: always
    build: ./mosquitto
    ports:
      - "1883:1883"
    labels:
      io.balena.features.supervisor-api: '1'

